### ISSUE TITLE
TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by ivanafanasyeu** [davidnguyen179/react-is-in-viewport#37]
Next.js + typescript

After cmd+shift+R issue is gone

**Comment by itsdarrylnorris** [comment]
This happens all the time when I change routes in my single-page application.

Here is the console error:
```
Uncaught TypeError: Cannot read properties of null (reading 'getBoundingClientRect')
    at Viewport._this.handleScroll (index.js?f5fe:83)
    at exec (throttle.js?fef0:67)
    at wrapper (throttle.js?fef0:93)
    
```


Here is where the actual error happens:
![Screen Shot 2021-10-14 at 3 57 43 PM](https://user-images.githubusercontent.com/6808460/137406592-67fb8db7-eab5-4f90-98fe-264682770286.png)

**Comment by ivanafanasyeu** [comment]
close due to inactivity
